apiVersion: apps/v1
kind: Deployment
metadata:
  name: mkdocs-dev
  labels:
    app: mkdocs-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mkdocs-dev
  template:
    metadata:
      labels:
        app: mkdocs-dev
    spec:
      containers:
      - name: mkdocs
        image: mkdocs-dev
        ports:
        - containerPort: 8000
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: MKDOCS_VERBOSE
          value: "1"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: docs-volume
          mountPath: /app/docs
          readOnly: false
        - name: config-volume
          mountPath: /app/mkdocs.yml
          subPath: mkdocs.yml
          readOnly: true
      volumes:
      - name: docs-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: mkdocs-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mkdocs-config
data:
  mkdocs.yml: |
    site_name: Harry's Blog 
    site_url: https://hien-p.github.io/hari-docs/ 
    
    strict: false
    use_directory_urls: true
    docs_dir: docs
    site_dir: site
    
    theme:  
      name: null
      custom_dir: mkdocs-windmill/mkdocs_windmill/
    
    extra_css:
      - css/custom.css
    
    plugins:
      - search:
          lang: en
          separator: '[\s\-,:!=\[\]()"/`|]+'
          prebuild_index: true
          indexing: 'full'
      - minify:
          minify_html: true
          minify_css: true
          minify_js: true
      - git-revision-date-localized:
          enable_creation_date: false
    
    markdown_extensions:
      - abbr
      - admonition
      - attr_list
      - def_list
      - footnotes
      - md_in_html
      - toc:
          permalink: true
          title: On this page
      - pymdownx.arithmatex:
          generic: true
      - pymdownx.betterem:
          smart_enable: all
      - pymdownx.caret
      - pymdownx.details
      - pymdownx.emoji:
          emoji_generator: !!python/name:pymdownx.emoji.to_svg
          emoji_index: !!python/name:material.extensions.emoji.twemoji
      - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
      - pymdownx.inlinehilite
      - pymdownx.keys
      - pymdownx.magiclink
      - pymdownx.mark
      - pymdownx.smartsymbols
      - pymdownx.snippets:
          check_paths: true
      - pymdownx.superfences:
          custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
      - pymdownx.tabbed:
          alternate_style: true
          combine_header_slug: true
          slugify: !!python/object/apply:pymdownx.slugs.slugify
            kwds:
              case: lower
      - pymdownx.tasklist:
          custom_checkbox: true
      - pymdownx.tilde
    
    extra:
      social:
        - icon: simple/youtube
          link: https://www.youtube.com/@Harry_Blockchain
