apiVersion: v1
kind: Service
metadata:
  name: mkdocs-dev-service
  labels:
    app: mkdocs-dev
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: mkdocs-dev
